---
title: "Markovid_diagnostic_plots"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE}
# read in diagnostics
diags <- readRDS("../ignore/output/diagnostics_mcmc4.rds")
df_params <- diags$df_params
```

## Credible intervals of all parameters

```{r, echo=FALSE, fig.width=9}
axis_rotate <- ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 90, hjust = 1))
diags$credible_all + axis_rotate
```

## Trace plots (including burn-in)

```{r, echo=FALSE, fig.width=9}
for (i in seq_along(diags$trace_both)) {
  plot_i <- diags$trace_both[[i]]$combined
  title <- cowplot::ggdraw() +
    cowplot::draw_label(sprintf("parameter: %s", df_params$name[i]), x = 0, hjust = 0) +
    ggplot2::theme(plot.margin = ggplot2::margin(0, 0, 0, 20))
  cp <- cowplot::plot_grid(title, plot_i, ncol = 1, rel_heights = c(0.1,1))
  print(cp)
}
```

## Trace plots (sampling only)

```{r, echo=FALSE, fig.width=9}
for (i in seq_along(diags$trace_sampling)) {
  plot_i <- diags$trace_sampling[[i]]$combined
  title <- cowplot::ggdraw() +
    cowplot::draw_label(sprintf("parameter: %s", df_params$name[i]), x = 0, hjust = 0) +
    ggplot2::theme(plot.margin = ggplot2::margin(0, 0, 0, 20))
  cp <- cowplot::plot_grid(title, plot_i, ncol = 1, rel_heights = c(0.1,1))
  print(cp)
}
```

